spring.application.name: uploader-service

server.servlet.context-path: /uploads
server.port: 9050
eureka.client.service-url.defaultZone: http://localhost:8761/eureka

cloudinary:
  cloud-name: dkhj1rghl
  api-key:
  api-secret:

gcs:
  bucket-name: cs-linkedin-prod
  access-account:
